In [135]:
import pandas as pd

df = pd.read_csv("../data/online_retail_II.csv")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [136]:
df.shape

(1067371, 8)

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [138]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [139]:
df.duplicated().sum()

34335

In [140]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

Week 1 – Day 3: Data Quality Assessment
Goal

Before deleting or modifying any data, we need to measure the quality of the dataset.

A good data analyst never starts cleaning without first understanding what needs cleaning.

Today's objectives are to:

Count missing Customer IDs.
Count duplicate rows.
Count cancelled transactions.
Count invalid quantities.
Count invalid prices.

These findings will justify our cleaning decisions in the notebook.

In [141]:
# Count missing values in each column
missing_values = df.isnull().sum()

print(missing_values)

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [142]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [143]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 34335

In [144]:
cancelled_orders = df[df["Invoice"].astype(str).str.startswith("C")]

print("Cancelled Transactions:", cancelled_orders.shape[0])

Cancelled Transactions: 19494

In [145]:
invalid_quantity = df[df["Quantity"] <= 0]

print("Quantity <= 0 :", invalid_quantity.shape[0])

Quantity <= 0 : 22950

In [146]:
invalid_price = df[df["Price"] <= 0]

print("Price <= 0 :", invalid_price.shape[0])

Price <= 0 : 6207

In [147]:
# Display all column names
print("Dataset Columns:")
for column in df.columns:
    print(column)

Dataset Columns:
Invoice
StockCode
Description
Quantity
InvoiceDate
Price
Customer ID
Country

In [148]:
# Count rows with missing Customer ID
missing_customer_ids = df["Customer ID"].isnull().sum()

print("Missing Customer IDs:", missing_customer_ids)

Missing Customer IDs: 243007

In [149]:
# Calculate the percentage of rows with missing Customer ID
missing_customer_percentage = (
    missing_customer_ids / len(df)
) * 100

print(
    "Missing Customer ID Percentage:",
    round(missing_customer_percentage, 2),
    "%"
)

Missing Customer ID Percentage: 22.77 %

In [150]:
# Count completely duplicated rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 34335

In [151]:
# Display sample duplicated records
df[df.duplicated(keep=False)].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

### Data Quality Findings

- The dataset contains missing Customer IDs, which cannot be used for customer-level cohort and CLTV analysis.
- Duplicate transaction rows may inflate revenue and purchase-frequency calculations.
- These issues will be handled in the next cleaning stage.

In [152]:
# Find invoices that start with "C"
cancelled_orders = df[df["Invoice"].astype(str).str.startswith("C")]

print("Cancelled Orders:", cancelled_orders.shape[0])

Cancelled Orders: 19494

In [153]:
invalid_quantity = df[df["Quantity"] <= 0]

print("Transactions with Quantity <= 0:", invalid_quantity.shape[0])

Transactions with Quantity <= 0: 22950

In [154]:
invalid_quantity.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [155]:
invalid_price = df[df["Price"] <= 0]

print("Transactions with Price <= 0:", invalid_price.shape[0])

Transactions with Price <= 0: 6207

In [156]:
invalid_price.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

## Data Quality Assessment

The dataset contains several transaction types that require cleaning before cohort analysis.

### Findings

- Cancelled invoices are identified by invoice numbers beginning with "C".
- Transactions with Quantity ≤ 0 represent returns, cancellations, or invalid entries.
- Transactions with Price ≤ 0 require further investigation before revenue calculations.

These records will be cleaned in the next stage before creating Cohort Month and CLTV metrics.

In [157]:
# Create a copy of the original dataset
clean_df = df.copy()

In [158]:
clean_df = clean_df.dropna(subset=["Customer ID"])

In [159]:
clean_df = clean_df.drop_duplicates()

In [160]:
clean_df = clean_df[
    ~clean_df["Invoice"].astype(str).str.startswith("C")
]

In [161]:
clean_df = clean_df[
    clean_df["Quantity"] > 0
]

In [162]:
clean_df = clean_df[
    clean_df["Price"] > 0
]

In [163]:
print("Original Dataset Shape :", df.shape)
print("Cleaned Dataset Shape  :", clean_df.shape)

Original Dataset Shape : (1067371, 8)
Cleaned Dataset Shape  : (779425, 8)

In [164]:
print("Missing Customer IDs :", clean_df["Customer ID"].isnull().sum())
print("Duplicate Rows       :", clean_df.duplicated().sum())
print("Invalid Quantity     :", (clean_df["Quantity"] <= 0).sum())
print("Invalid Price        :", (clean_df["Price"] <= 0).sum())

Missing Customer IDs : 0
Duplicate Rows       : 0
Invalid Quantity     : 0
Invalid Price        : 0

## Data Cleaning Summary

The original dataset contained several data quality issues that could affect customer retention and CLTV analysis.

The following cleaning steps were performed:

- Removed records with missing Customer IDs.
- Removed duplicate transaction records.
- Removed cancelled invoices.
- Removed transactions with non-positive quantities.
- Removed transactions with non-positive prices.

The cleaned dataset will be used for all subsequent cohort and CLTV calculations.

In [165]:
# Convert InvoiceDate from text/object format to datetime format
clean_df["InvoiceDate"] = pd.to_datetime(
    clean_df["InvoiceDate"],
    errors="coerce"
)

In [166]:
# Count invalid or missing dates after conversion
invalid_dates = clean_df["InvoiceDate"].isna().sum()

print("Invalid Invoice Dates:", invalid_dates)

Invalid Invoice Dates: 0

In [167]:
clean_df[clean_df["InvoiceDate"].isna()].head()

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [168]:
# Calculate revenue generated by each transaction row
clean_df["Revenue"] = (
    clean_df["Quantity"] * clean_df["Price"]
)

In [169]:
clean_df[
    ["Invoice", "Quantity", "Price", "Revenue"]
].head()

  Invoice  Quantity  Price  Revenue
0  489434        12   6.95     83.4
1  489434        12   6.75     81.0
2  489434        12   6.75     81.0
3  489434        48   2.10    100.8
4  489434        24   1.25     30.0

In [170]:
# Extract the calendar month of each transaction
clean_df["InvoiceMonth"] = (
    clean_df["InvoiceDate"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

In [171]:
clean_df[
    [
        "InvoiceDate",
        "InvoiceMonth",
        "Quantity",
        "Price",
        "Revenue"
    ]
].head()

          InvoiceDate InvoiceMonth  Quantity  Price  Revenue
0 2009-12-01 07:45:00   2009-12-01        12   6.95     83.4
1 2009-12-01 07:45:00   2009-12-01        12   6.75     81.0
2 2009-12-01 07:45:00   2009-12-01        12   6.75     81.0
3 2009-12-01 07:45:00   2009-12-01        48   2.10    100.8
4 2009-12-01 07:45:00   2009-12-01        24   1.25     30.0

In [172]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 779425 entries, 0 to 1067370
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       779425 non-null  object
 1   StockCode     779425 non-null  object
 2   Description   779425 non-null  object
 3   Quantity      779425 non-null  int64
 4   InvoiceDate   779425 non-null  datetime64[ns]
 5   Price         779425 non-null  float64
 6   Customer ID   779425 non-null  float64
 7   Country       779425 non-null  object
 8   Revenue       779425 non-null  float64
 9   InvoiceMonth  779425 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(4)
memory usage: 65.4+ MB

In [173]:
print("Minimum Revenue:", clean_df["Revenue"].min())
print("Maximum Revenue:", clean_df["Revenue"].max())
print("Total Revenue:", clean_df["Revenue"].sum())

print(
    "Transaction Period:",
    clean_df["InvoiceDate"].min(),
    "to",
    clean_df["InvoiceDate"].max()
)

Minimum Revenue: 0.001
Maximum Revenue: 168469.6
Total Revenue: 17374804.268000003
Transaction Period: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

## Revenue and Date Preparation

The cleaned transaction dates were converted to a proper datetime format so that monthly customer activity can be analyzed accurately.

A Revenue column was calculated using:

Revenue = Quantity × Price

The InvoiceMonth field was then created by reducing each transaction date to its corresponding calendar month. These fields will support cohort assignment, retention analysis, and CLTV calculations.

In [174]:
# Find the first purchase month for each customer
cohort_data = clean_df.groupby("Customer ID")["InvoiceMonth"].min()

cohort_data.head()

Customer ID
12346.0   2009-12-01
12347.0   2010-10-01
12348.0   2010-09-01
12349.0   2010-04-01
12350.0   2011-02-01
Name: InvoiceMonth, dtype: datetime64[ns]

In [175]:
cohort_data = cohort_data.rename("CohortMonth")

In [176]:
clean_df = clean_df.merge(
    cohort_data,
    on="Customer ID"
)

clean_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,InvoiceMonth,CohortMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009-12-01,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12-01,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12-01,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009-12-01,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009-12-01,2009-12-01

In [177]:
clean_df[
    [
        "Customer ID",
        "InvoiceMonth",
        "CohortMonth"
    ]
].head(15)

    Customer ID InvoiceMonth CohortMonth
0       13085.0   2009-12-01  2009-12-01
1       13085.0   2009-12-01  2009-12-01
2       13085.0   2009-12-01  2009-12-01
3       13085.0   2009-12-01  2009-12-01
4       13085.0   2009-12-01  2009-12-01
5       13085.0   2009-12-01  2009-12-01
6       13085.0   2009-12-01  2009-12-01
7       13085.0   2009-12-01  2009-12-01
8       13085.0   2009-12-01  2009-12-01
9       13085.0   2009-12-01  2009-12-01
10      13085.0   2009-12-01  2009-12-01
11      13085.0   2009-12-01  2009-12-01
12      13085.0   2009-12-01  2009-12-01
13      13085.0   2009-12-01  2009-12-01
14      13085.0   2009-12-01  2009-12-01

In [178]:
print(
    "Number of Cohorts:",
    clean_df["CohortMonth"].nunique()
)

Number of Cohorts: 25

## Cohort Assignment

Each customer was assigned to a cohort based on the month of their first recorded purchase.

The CohortMonth remains fixed for every customer regardless of subsequent purchases.

This allows customers acquired during the same month to be analysed together throughout the remainder of the project.

In [179]:
# Extract year and month from InvoiceMonth
invoice_year = clean_df["InvoiceMonth"].dt.year
invoice_month = clean_df["InvoiceMonth"].dt.month

# Extract year and month from CohortMonth
cohort_year = clean_df["CohortMonth"].dt.year
cohort_month = clean_df["CohortMonth"].dt.month

In [180]:
clean_df["CohortIndex"] = (
    (invoice_year - cohort_year) * 12
    + (invoice_month - cohort_month)
)

In [181]:
clean_df[
    [
        "Customer ID",
        "CohortMonth",
        "InvoiceMonth",
        "CohortIndex"
    ]
].head(20)

    Customer ID CohortMonth InvoiceMonth  CohortIndex
0       13085.0  2009-12-01   2009-12-01            0
1       13085.0  2009-12-01   2009-12-01            0
2       13085.0  2009-12-01   2009-12-01            0
3       13085.0  2009-12-01   2009-12-01            0
4       13085.0  2009-12-01   2009-12-01            0
5       13085.0  2009-12-01   2009-12-01            0
6       13085.0  2009-12-01   2009-12-01            0
7       13085.0  2009-12-01   2009-12-01            0
8       13085.0  2009-12-01   2009-12-01            0
9       13085.0  2009-12-01   2009-12-01            0
10      13085.0  2009-12-01   2009-12-01            0
11      13085.0  2009-12-01   2009-12-01            0
12      13085.0  2009-12-01   2009-12-01            0
13      13085.0  2009-12-01   2009-12-01            0
14      13085.0  2009-12-01   2009-12-01            0
15      13085.0  2009-12-01   2009-12-01            0
16      13085.0  2009-12-01   2009-12-01            0
17      13085.0  2009-12-01   2009-12-01            0
18      13085.0  2009-12-01   2009-12-01            0
19      13085.0  2009-12-01   2009-12-01            0

In [182]:
print("Minimum Cohort Index:", clean_df["CohortIndex"].min())
print("Maximum Cohort Index:", clean_df["CohortIndex"].max())

Minimum Cohort Index: 0
Maximum Cohort Index: 24

In [183]:
negative_index = clean_df[clean_df["CohortIndex"] < 0]

print("Negative Cohort Index:", len(negative_index))

Negative Cohort Index: 0

## Cohort Index Calculation

The Cohort Index represents the number of months since each customer's first purchase.

- Month 0 represents the acquisition month.
- Month 1 represents one month after acquisition.
- Month 2 represents two months after acquisition.

The Cohort Index is used to measure customer retention over time and forms the basis of the cohort retention matrix.

In [184]:
# Count unique customers for each Cohort Month and Cohort Index
cohort_counts = (
    clean_df
    .groupby(["CohortMonth", "CohortIndex"])["Customer ID"]
    .nunique()
)

In [185]:
cohort_counts.head(15)

CohortMonth  CohortIndex
2009-12-01   0              955
             1              337
             2              319
             3              406
             4              363
             5              343
             6              360
             7              327
             8              321
             9              346
             10             403
             11             473
             12             359
             13             270
             14             233
Name: Customer ID, dtype: int64

In [190]:
cohort_matrix = cohort_counts.unstack(fill_value=0)

In [187]:
cohort_matrix.head()

CohortIndex,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
CohortMonth,,,,,,,,,,,,,,,,,,,,,
2009-12-01,955,337,319,406,363,343,360,327,321,346,...,289,251,289,270,248,244,301,291,389,188
2010-01-01,383,79,119,117,101,115,99,88,107,122,...,58,90,76,71,75,93,74,94,22,0
2010-02-01,374,89,84,109,92,75,72,107,95,103,...,75,60,61,54,86,86,61,22,0,0
2010-03-01,443,84,102,107,103,90,109,134,122,48,...,75,77,69,78,89,94,35,0,0,0
2010-04-01,294,57,57,48,54,66,81,77,31,32,...,46,41,44,53,66,17,0,0,0,0

In [188]:
print("Matrix Shape:", cohort_matrix.shape)

Matrix Shape: (25, 25)

In [189]:
print(cohort_matrix.iloc[:, 0].head())

CohortMonth
2009-12-01    955
2010-01-01    383
2010-02-01    374
2010-03-01    443
2010-04-01    294
Name: 0, dtype: int64

## Cohort Retention Matrix

The transaction data was grouped by:

- Cohort Month
- Cohort Index

The number of unique customers was calculated for every cohort and every month after acquisition.

The resulting matrix forms the foundation for calculating customer retention percentages.